### PR TITLE
Update load config files

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
#### New standard load config files. If there is an error during the download. You'll know.

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Nice

**Comment by BarbzYHOOL** [comment]
Very good idea ayasecore

**Comment by Winfidonarleyan** [comment]
I don't quite understand the idea of ayasecore

**Comment by BarbzYHOOL** [comment]
Me neither, I just wanted to sound cool.

Na, joking.

In fact, he wants to create some kind of preset function or something like that so we just need to write one line to enable configuration.

So it will be cleaner

**Comment by BarbzYHOOL** [comment]
Until a better solution is found, this is going to be merged.

Rochet2 also suggested to add directly something in the core for module confs.

**Comment by AyaseCore** [comment]
-_ -! My English is bad.
So people often don't understand what I'm trying to say.
And I often don't understand what people are trying to say. @Winfidonarleyan 
In fact, I was surprised that @BarbzYHOOL  could understand what I said.  XXXD

**Pull request merged**
