### PR TITLE
Set sql/ dir structure for dev and prod environments

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
Need some feedback on this.

I would personally use this.

I tried to make it clear from the names what each dir can be used for.

Dir structure:

```
├── CMakeLists.txt
├── conf
│   └── my_custom.conf.dist
├── include.sh
├── README.md
├── setup_git_commit_template.sh
├── sql
│   ├── data
│   │   ├── auth
│   │   │   ├── development
│   │   │   │   └── delete_me.sql
│   │   │   └── production
│   │   │       └── delete_me.sql
│   │   ├── characters
│   │   │   ├── development
│   │   │   │   └── delete_me.sql
│   │   │   └── production
│   │   │       └── delete_me.sql
│   │   ├── README.md
│   │   └── world
│   │       ├── development
│   │       │   └── delete_me.sql
│   │       └── production
│   │           └── delete_me.sql
│   ├── README.md
│   └── structure
│       ├── auth
│       │   └── delete_me.sql
│       ├── characters
│       │   └── delete_me.sql
│       ├── README.md
│       └── world
│           └── delete_me.sql
└── src
    ├── loader.h
    └── MyPlayer.cpp
```

I wanted to set a dir structure that makes people think "hey that's a good idea to put this into this dir"

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Why not use the same directory structure as the core and include an example for use with db_assembler? At least this is what the "custom" option of the db_assembler script is all about (e.g. Transmog and Beastmaster are already using this system).
```
data/sql/db-auth
data/sql/db-characters
data/sql/db-world
data/sql/updates/db-auth
data/sql/updates/db-characters
data/sql/updates/db-world
```
include.sh:
```bash
#!/usr/bin/env bash

MOD_SKELETON_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/" && pwd )"

source $MOD_SKELETON_ROOT"/conf/conf.sh.dist"

if [ -f $MOD_SKELETON_ROOT"/conf/conf.sh" ]; then
    source $MOD_SKELETON_ROOT"/conf/conf.sh"
fi
```
conf/conf.sh.dist:
```bash
#!/usr/bin/env bash

#
# CUSTOM
#

DB_WORLD_CUSTOM_PATHS+=(
	$MOD_SKELETON_ROOT"/data/sql/db-auth/"
	$MOD_SKELETON_ROOT"/data/sql/db-characters/"
	$MOD_SKELETON_ROOT"/data/sql/db-world/"
)

#
# UPDATES
#

DB_WORLD_UPDATE_PATHS+=(
	$MOD_SKELETON_ROOT"/data/sql/updates/db-auth/"
	$MOD_SKELETON_ROOT"/data/sql/updates/db-characters/"
	$MOD_SKELETON_ROOT"/data/sql/updates/db-world/"
)
```

**Comment by BarbzYHOOL** [comment]
I think this is for another PR/issue and can be combined with the actual PR.

My goal here is to separate development and production (for example when we put a dummy.sql to test a module), and then we can update the bash script to reflect that.

**Comment by milestorme** [comment]
That’s actually a really good idea , I like it

**Comment by BarbzYHOOL** [comment]
New sql dir structure:

```
├── auth
│   ├── development.sql
│   ├── production.sql
│   └── structure.sql
├── characters
│   ├── development.sql
│   ├── production.sql
│   └── structure.sql
├── README.md
└── world
    ├── development.sql
    ├── production.sql
    └── structure.sql
```

People can delete the files if not needed.

**Comment by Winfidonarleyan** [comment]
I like this

**Comment by Deku** [comment]
I fail to see the benefit to separate production and development. Wouldn't it add another thing to worry about? (going against KISS)

Also, in databases you use the term "schema" to refer to the structure of the db

**Comment by BarbzYHOOL** [comment]
put data in development.sql for testing stuff
put data in production.sql when it's required for the module to work 

else if you don't understand what it's for, you can delete it but the name by itself (+ the comment) would help people to understand the use and then they can think "ah ok i can do this"


that's how I discovered about prod/dev/test too on another framework

**Comment by wizzymore** [comment]
I think this can be merged after: https://github.com/azerothcore/skeleton-module/pull/15

**Comment by BarbzYHOOL** [comment]
build error:

```sh
NOTICE: file </home/travis/build/azerothcore/azerothcore-wotlk/conf/config.sh> has not been found, you should create and configure it.

/home/travis/build/azerothcore/azerothcore-wotlk/modules/skeleton-module/include.sh: line 2: $'\r': command not found
```

**Comment by wizzymore** [comment]
Everything fixed now

**Pull request merged**
